# Generated by Django 3.2.16 on 2022-11-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.IntegerField(blank=True, default=1, verbose_name='Venue Owner'),
        ),
    ]
